packages:
  - '.'
  - 'examples/nuxt'
  - 'examples/next'

catalog:
  '@better-auth/core': ^1.6.14
  better-auth: ^1.6.14
  better-call: ^2.0.3
  zod: ^4.4.3

allowBuilds:
  '@parcel/watcher': true
  better-sqlite3: true
  esbuild: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
